version: "3.8"
services:
  golang-backend:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    container_name: golang-backend-test
    environment:
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}  
    ports:
      - 8080:8080
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres:latest
    container_name: db-postgres-test
    environment:
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
    ports:
      - '5432:5432'